name: Deploy to Staging from Development

on:
  push:
    branches:
      - stage
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy Frontend to Staging
    runs-on: [self-hosted, Staging]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set Environment Variables
        run: echo "VITE_API_URL=${{ secrets.VITE_ENVIRONMENT_STAGING }}" >> $GITHUB_ENV

      - name: Install dependencies and build
        run: |
          npm install
          npm run build -- --mode staging
          ls -la dist

      - name: Sync build to VPS folder
        run: |
          # Adjust this path if your nginx root differs
          sudo mkdir -p __FRONTEND_DEPLOY_PATH_STAGING__
          sudo find "__FRONTEND_DEPLOY_PATH_STAGING__" \
          -mindepth 1 \
          -maxdepth 1 \
          ! -name "myapps" \
          -exec rm -rf {} +
          sudo cp -a dist/. __FRONTEND_DEPLOY_PATH_STAGING__/

      - name: Restart nginx
        run: sudo service nginx restart
